import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
// import ptBR from '../public/locales/ptBR';
// import ptBR from '../public/locales/ptBR'

const ptBR = {

  "YEAR": "ANO",
  "CATEGORIES": "CATEGORIAS",
  "DESCRIPTION": "DESCRIÇÃO",
  "OBJECTIVES": "OBJETIVOS",

  "Hello,": "Olá,",
  "Thank you for visiting my portfolio website. I am passionate about design and coding, and I'm excited to showcase my work and skills to you.": "Obrigado por visitar o meu site de portfólio. Sou apaixonado por design e programação, e estou empolgado em apresentar meu trabalho e habilidades a você.",
  "I am a versatile professional with a strong background in both design and programming. My journey began with a love for creating visually appealing designs, and over the years, I've honed my coding skills to bring those designs to life. My mission is to create meaningful and innovative digital experiences that leave a lasting impression.": "Sou um profissional versátil com sólida formação em design e programação. Minha jornada começou com um amor por criar designs visualmente atraentes, e ao longo dos anos, aprimorei minhas habilidades de programação para dar vida a esses designs. Minha missão é criar experiências digitais significativas e inovadoras que deixem uma impressão duradoura.",
  "I have a solid background in Advertising and Marketing, which provides me with a unique perspective when it comes to creating engaging and effective digital experiences.": "Além da minha paixão por design e programação, tenho uma formação sólida em Publicidade e Propaganda, o que me proporciona uma visão única quando se trata de criar experiências digitais envolventes e eficazes.",
  "My skill set includes expertise in various areas, such as:": "O meu conjunto de habilidades inclui especialização em diversas áreas, tais como:",
  "Development": "Desenvolvimento",
  "Design & Prototype:": "Design & Prototipagem:",
  "I am committed to delivering innovative and functional solutions that meet my clients needs and provide memorable experiences for users. If you are looking for a versatile and passionate professional, I am available to collaborate on challenging and inspiring projects. Let's create something amazing together!": "Estou comprometido em fornecer soluções inovadoras e funcionais que atendam às necessidades dos meus clientes e proporcionem experiências memoráveis para os usuários. Se você procura um profissional versátil e apaixonado, estou disponível para colaborar em projetos desafiadores e inspiradores. Vamos criar algo incrível juntos!",
  "Back": "Voltar",
  "Social Media and Design - Campinas Power Challenge": "Redes Sociais e Design - Campinas Power Challenge",

  // **** JOBS

  // **** Social Media and Design - Campinas Power Challenge

  "<p>In the thrilling world of CrossFit, effective communication is as crucial as strength and endurance. In this design project, I fully immersed myself in the challenge of portraying the intensity, passion, and energy of a CrossFit sporting event, transforming them into images that stand out and engage the audience. The event took place in December 2016 in Campinas, SP.</p>": "<p>No emocionante mundo do CrossFit, a comunicação eficaz é tão crucial quanto a força e a resistência. Neste projeto de design, eu me envolvi completamente no desafio de retratar a intensidade, paixão e energia de um evento esportivo de CrossFit, transformando-os em imagens que se destacam e envolvem o público. O evento ocorreu em dezembro de 2016 em Campinas, SP.</p>",

  "<p>• Create a cohesive and exciting visual identity for the CrossFit sporting event.</p><p>• Develop compelling designs that convey the strength, determination, and competitive spirit of the athletes.</p><p>• Utilize colors, typography, and graphic elements that capture the essence of CrossFit.</p><p>• Enhance the online presence of the event, increasing viewer engagement and participation.</p>": "<p>• Criar uma identidade visual coesa e emocionante para o evento esportivo de CrossFit.</p><p>• Desenvolver designs cativantes que transmitam a força, determinação e espírito competitivo dos atletas.</p><p>• Utilizar cores, tipografia e elementos gráficos que capturem a essência do CrossFit.</p><p>• Aprimorar a presença online do evento, aumentando o engajamento e a participação dos espectadores.</p>",

  // **** Social Media - Jarras Gorre

  "<p>In this social media project, I immersed myself in the challenge of revealing the life-enhancing properties of water alkalizing pitchers. The posts serve as a path to a healthier and more vibrant lifestyle.</p>": "<p>Neste projeto de redes sociais, mergulhei no desafio de revelar as propriedades que melhoram a vida das jarras alcalinizadoras de água. As postagens servem como um caminho para um estilo de vida mais saudável e vibrante.</p>",

  "<p>• Create visually captivating and informative posts for social media.</p><p>• Develop content that highlights the life-enhancing benefits of alkaline water for health and well-being.</p><p>• Utilize colors, images, and graphic elements that convey a sense of purity, vitality, and holistic well-being associated with alkaline water.</p><p>• Enhance the online presence by providing content that inspires the quest for healthier hydration, educating the community about the body and mind benefits of alkaline water.</p>": "<p>• Criar postagens visualmente cativantes e informativas para redes sociais.</p><p>• Desenvolver conteúdo que destaque os benefícios que melhoram a vida da água alcalina para a saúde e o bem-estar.</p><p>• Utilizar cores, imagens e elementos gráficos que transmitam uma sensação de pureza, vitalidade e bem-estar holístico associados à água alcalina.</p><p>• Aprimorar a presença online fornecendo conteúdo que inspire a busca por uma hidratação mais saudável, educando a comunidade sobre os benefícios para o corpo e a mente da água alcalina.</p>",

  // **** Social Media and Design - Premium Cup BJJ - 5ª Edição

  "<p>In August 2018, Campinas became the epicenter of the jiu-jitsu world with a breathtaking championship. It was a celebration of strength, technique, and determination, where the best athletes faced each other on the mats in pursuit of glory. The event was an unforgettable experience that brought together the jiu-jitsu community in Campinas and beyond.</p>": "<p>Em agosto de 2018, Campinas se tornou o epicentro do mundo do jiu-jitsu com um campeonato de tirar o fôlego. Foi uma celebração de força, técnica e determinação, onde os melhores atletas se enfrentaram nos tatames em busca da glória. O evento foi uma experiência inesquecível que reuniu a comunidade de jiu-jitsu em Campinas e além.</p>",

  "<p>• Share the passion, excitement, and intense competition of jiu-jitsu with our community.</p><p>• Highlight the talents and achievements of the athletes who participated in this exciting championship.</p><p>• Provide essential information about the event, such as dates, venues, and registration details.</p><p>The social media graphics created for this event captured the unique energy of jiu-jitsu and were designed to engage and inspire both participants and enthusiasts of this passionate sport.</p>": "<p>• Compartilhar a paixão, empolgação e intensa competição do jiu-jitsu com nossa comunidade.</p><p>• Destacar os talentos e conquistas dos atletas que participaram deste empolgante campeonato.</p><p>• Fornecer informações essenciais sobre o evento, como datas, locais e detalhes de inscrição.</p><p>Os gráficos de mídia social criados para este evento capturaram a energia única do jiu-jitsu e foram projetados para envolver e inspirar tanto participantes quanto entusiastas deste esporte apaixonado.</p>",

  // **** Social Media and Design - InVita Formulas

  "<p>In the innovative field of compounding pharmacy, effective communication is as crucial as precision in crafting personalized medications. In our social media projects, we delve deep into the challenge of conveying quality, health, and well-being, transforming these elements into posts that stand out and engage the audience.</p>": "<p>No inovador campo da farmácia de manipulação, a comunicação eficaz é tão crucial quanto a precisão na elaboração de medicamentos personalizados. Em nossos projetos de mídia social, mergulhamos profundamente no desafio de transmitir qualidade, saúde e bem-estar, transformando esses elementos em postagens que se destacam e envolvem o público.</p>",

  "<p>• Create visually appealing and informative posts for the Compounding Pharmacy's social media.</p><p>• Develop content that conveys dedication to the health, quality, and well-being of our customers.</p><p>• Utilize colors, images, and graphic elements that capture the essence of the compounding pharmacy, reflecting the mission of providing tailored health solutions.</p><p>• Enhance our online presence by providing content that encourages the discovery of customized products, health education, and engagement with a community interested in improving their quality of life through tailor-made pharmaceutical solutions.</p>":"<p>• Criar postagens visualmente atrativas e informativas para as redes sociais da Farmácia de Manipulação.</p><p>• Desenvolver conteúdo que transmita dedicação à saúde, qualidade e bem-estar de nossos clientes.</p><p>• Utilizar cores, imagens e elementos gráficos que capturem a essência da farmácia de manipulação, refletindo a missão de fornecer soluções de saúde personalizadas.</p><p>• Aprimorar nossa presença online oferecendo conteúdo que incentive a descoberta de produtos personalizados, educação em saúde e engajamento com uma comunidade interessada em melhorar sua qualidade de vida por meio de soluções farmacêuticas feitas sob medida.</p>",

  // **** Social Media and Design - Big Wars BJJ - Ed. 2

  "<p>In March 2023, the Campinas region became the epicenter of jiu-jitsu excellence with a showcase of superlative talent in the gentle art. It was a celebration of technique, passion, and unwavering commitment to the sport, where the best instructors engaged in epic battles on the mats. The event was an unparalleled experience, uniting the jiu-jitsu community and offering moments of pure inspiration and triumph.</p>":"<p>Em março de 2023, a região de Campinas se tornou o epicentro da excelência do jiu-jitsu com uma exibição de talento superlativo na arte suave. Foi uma celebração de técnica, paixão e comprometimento inabalável com o esporte, onde os melhores instrutores se engajaram em batalhas épicas nos tatames. O evento foi uma experiência incomparável, unindo a comunidade de jiu-jitsu e oferecendo momentos de pura inspiração e triunfo.</p>",

  "<p>• Highlight the mastery and expertise of the best instructors in the Campinas region.</p><p>• Disseminate vital information about the event, including date, location, and participants.</p><p>• Celebrate the determination and sportsmanship that make jiu-jitsu a unique and inspiring discipline.</p>":"<p>• Destacar a maestria e expertise dos melhores instrutores na região de Campinas.</p><p>• Disseminar informações vitais sobre o evento, incluindo data, local e participantes.</p><p>• Celebrar a determinação e o espírito esportivo que tornam o jiu-jitsu uma disciplina única e inspiradora.</p>",

  // **** Site WordPress - Instituto Conexões

  "<p>In the enriching world of psychoanalysis, effective communication is as essential as understanding and empathy. In this WordPress website project, I fully immersed myself in the challenge of conveying the depth, empathy, and knowledge of a psychoanalytic institute, transforming these elements into a website that stands out and engages visitors. The institute serves as a beacon of wisdom and understanding, and this website is its virtual window to the world.</p><p><strong>Link para o site:</strong> <a href='https://www.institutoconexoes.com.br/' rel='noopener noreferrer' target='_blank'>www.institutoconexoes.com.br</a></p>":"<p>No enriquecedor mundo da psicanálise, a comunicação eficaz é tão essencial quanto a compreensão e empatia. Neste projeto de site WordPress, mergulhei completamente no desafio de transmitir a profundidade, empatia e conhecimento de um instituto psicanalítico, transformando esses elementos em um site que se destaca e envolve os visitantes. O instituto serve como um farol de sabedoria e compreensão, e este site é sua janela virtual para o mundo.</p><p><strong>Link para o site:</strong> <a href='https://www.institutoconexoes.com.br/' rel='noopener noreferrer' target='_blank'>www.institutoconexoes.com.br</a></p>",

  "<p>• Create a cohesive and informative visual identity for the Psychoanalytic Institute.</p><p>• Develop compelling designs that convey the empathy, knowledge, and compassion that are fundamental to psychoanalysis.</p><p>• Use colors, typography, and graphic elements that capture the essence of psychoanalysis, reflecting its welcoming and profound character.</p><p>• Enhance the online presence of the institute, providing a space that encourages exploration, learning, and engagement for visitors interested in psychoanalysis.</p>":"<p>• Criar uma identidade visual coesa e informativa para o Instituto Psicanalítico.</p><p>• Desenvolver designs cativantes que transmitam a empatia, conhecimento e compaixão que são fundamentais para a psicanálise.</p><p>• Utilizar cores, tipografia e elementos gráficos que capturem a essência da psicanálise, refletindo seu caráter acolhedor e profundo.</p><p>• Aprimorar a presença online do instituto, fornecendo um espaço que encoraje a exploração, aprendizado e engajamento para visitantes interessados na psicanálise.</p>",

  // **** Site WordPress - KinSol Sumaré

  "<p>In the transformative world of solar energy, effective communication is as vital as harnessing the power of the sun. In this web project, we fully immersed ourselves in the challenge of portraying the innovation, sustainability, and eco-consciousness of a solar energy company, transforming these elements into a website that shines and engages our audience. Our company serves as a beacon of clean, renewable power, and this website is your virtual gateway to a greener future.</p><p><strong>Link do site:</strong> <a href='https://www.kinsolsumare.com.br' rel='noopener noreferrer' target='_blank'>www.kinsolsumare.com.br</a></p>":"<p>No mundo transformador da energia solar, a comunicação eficaz é tão vital quanto aproveitar o poder do sol. Neste projeto web, nos imergimos completamente no desafio de retratar a inovação, sustentabilidade e consciência ambiental de uma empresa de energia solar, transformando esses elementos em um site que brilha e envolve nosso público. Nossa empresa serve como um farol de energia limpa e renovável, e este site é seu portal virtual para um futuro mais verde.</p><p><strong>Link do site:</strong> <a href='https://www.kinsolsumare.com.br' rel='noopener noreferrer' target='_blank'>www.kinsolsumare.com.br</a></p>",

  "<p>• Create a cohesive and informative visual identity for the Solar Energy Company.</p><p>• Develop compelling designs that convey the innovation, sustainability, and environmental consciousness that are fundamental to solar energy.</p><p>• Utilize colors, typography, and graphic elements that capture the essence of solar energy, reflecting its commitment to a cleaner and brighter world.</p><p>• Enhance the online presence of the company, providing a space that encourages exploration, learning, and engagement for individuals interested in harnessing the power of the sun for a more sustainable future.</p>":"<p>• Criar uma identidade visual coesa e informativa para a Empresa de Energia Solar.</p><p>• Desenvolver designs cativantes que transmitam a inovação, sustentabilidade e consciência ambiental que são fundamentais para a energia solar.</p><p>• Utilizar cores, tipografia e elementos gráficos que capturem a essência da energia solar, refletindo seu compromisso com um mundo mais limpo e brilhante.</p><p>• Aprimorar a presença online da empresa, fornecendo um espaço que encoraje a exploração, aprendizado e engajamento para pessoas interessadas em aproveitar o poder do sol para um futuro mais sustentável.</p>",

  // **** Social Media - Rio 40º

  "<p>• Share our passion for cuisine, mixology, and hospitality with the community of Campinas and beyond.</p><p>• Showcase the variety of delicious dishes, creative drinks, and unique gastronomic experiences.</p><p>• Keep our customers informed about special events, promotions, and exciting updates.</p>":"<p>• Compartilhar nossa paixão pela culinária, mixologia e hospitalidade com a comunidade de Campinas e além.</p><p>• Mostrar a variedade de pratos deliciosos, bebidas criativas e experiências gastronômicas únicas.</p><p>• Manter nossos clientes informados sobre eventos especiais, promoções e atualizações emocionantes.</p>",

  // **** Site WordPress - Dra. Christiana Blattner

  "<p>This project aimed to create an online presence that reflects the commitment to skin health and well-being. We developed a website that combines elegance and functionality, providing patients and visitors with an informative and welcoming experience. The website highlights specialized services, provides educational information on skincare, and maintains a modern and professional aesthetic.</p><p><strong>Project carried out for FastJobs Agency.</strong></p><p><strong>Link: </strong><a href='https://www.christianablattner.com.br/' rel='noopener noreferrer' target='_blank'>https://www.christianablattner.com.br/</a></p>":"<p>Este projeto teve como objetivo criar uma presença online que reflita o compromisso com a saúde e bem-estar da pele. Desenvolvemos um site que combina elegância e funcionalidade, oferecendo aos pacientes e visitantes uma experiência informativa e acolhedora. O site destaca serviços especializados, fornece informações educacionais sobre cuidados com a pele e mantém uma estética moderna e profissional.</p><p><strong>Projeto realizado para a Agência FastJobs.</strong></p><p><strong>Link: </strong><a href='https://www.christianablattner.com.br/' rel='noopener noreferrer' target='_blank'>https://www.christianablattner.com.br/</a></p>",

  // **** Site WordPress - JNK Portas Automáticas

  "<p>I developed a website that combines elegance and functionality, reflecting the quality and innovation the company offers in its products. The site features detailed catalogs of roll-up automatic doors, comprehensive technical information, and an intuitive user experience to facilitate navigation.</p><p><strong>Project carried out for FastJobs Agency.</strong></p><p><strong>Link: </strong><a href='https://comercialjnk.com.br/' rel='noopener noreferrer' target='_blank'>https://comercialjnk.com.br/</a></p>":"<p>Desenvolvi um site que combina elegância e funcionalidade, refletindo a qualidade e inovação que a empresa oferece em seus produtos. O site apresenta catálogos detalhados de portas automáticas de enrolar, informações técnicas abrangentes e uma experiência de usuário intuitiva para facilitar a navegação.</p><p><strong>Projeto realizado para a Agência FastJobs.</strong></p><p><strong>Link: </strong><a href='https://comercialjnk.com.br/' rel='noopener noreferrer' target='_blank'>https://comercialjnk.com.br/</a></p>",

  // **** Site WordPress - Lapa Doces

  "<p>The website features a comprehensive catalog of products, from ingredients to utensils. Additionally, it offers a streamlined shopping experience with detailed information on each item.</p><p>Link: <a href='https://www.lapadoces.com.br' rel='noopener noreferrer' target='_blank'>www.lapadoces.com.br</a></p>":"<p>O site apresenta um catálogo abrangente de produtos, desde ingredientes até utensílios. Além disso, oferece uma experiência de compra simplificada com informações detalhadas sobre cada item.</p><p>Link: <a href='https://www.lapadoces.com.br' rel='noopener noreferrer' target='_blank'>www.lapadoces.com.br</a></p>",

  // **** React.js + Node.js - Sneakers House

  "<p>Project developed during the course at Digital House, spanning a nine-month period. The outcome is an e-commerce platform specializing in collectible sneakers from various brands. To meet this challenge, we employed technologies such as Node.js with Express.js and Sequelize.js in the backend, while on the frontend, we utilized React.js with Axios and Redux. The system is supported by a robust SQL database.</p><p>In addition to the online store, we created an administrative interface, enabling the insertion, editing, and deletion of products, as well as efficient order management.</p>":"<p>Projeto desenvolvido durante o curso na Digital House, abrangendo um período de nove meses. O resultado é uma plataforma de e-commerce especializada em tênis colecionáveis de diversas marcas. Para enfrentar esse desafio, empregamos tecnologias como Node.js com Express.js e Sequelize.js no backend, enquanto no frontend utilizamos React.js com Axios e Redux. O sistema é suportado por um banco de dados SQL robusto.</p><p>Além da loja online, criamos uma interface administrativa, possibilitando a inserção, edição e exclusão de produtos, assim como uma gestão eficiente de pedidos.</p>",

  // **** Administrative Portfolio Dashboard

  "<p>Streamlining the everyday tasks of adding, editing, and removing categories and projects in your portfolio, I've crafted a user-friendly administrative dashboard. This sleek panel features Next Auth authentication for secure access and seamlessly communicates with the Node.js backend, ensuring effortless updates to your SQL database.</p><p><br></p><p>The libraries used were:</p><p><br></p><p>Front-End:</p><p>- Material UI</p><p>- I18Next</p><p>- Next Auth</p><p>- React Dom</p><p>- React Dropzone</p><p>- React Hook Form</p><p>- React toastfy</p><p>- Slate React</p><p><br></p><p>Back-End:</p><p>- BCrypt</p><p>- Cors</p><p>- Express</p><p>- JWT</p><p>- Multer</p><p>- MySql2</p><p>- Sequelize</p>":"<p>Para simplificar as tarefas diárias de adicionar, editar e remover categorias e projetos em seu portfólio, criei um painel administrativo amigável ao usuário. Este painel elegante apresenta autenticação Next Auth para acesso seguro e se comunica perfeitamente com o backend Node.js, garantindo atualizações sem esforço em seu banco de dados SQL.</p><p><br></p><p>As bibliotecas utilizadas foram:</p><p><br></p><p>Front-End:</p><p>- Material UI</p><p>- I18Next</p><p>- Next Auth</p><p>- React Dom</p><p>- React Dropzone</p><p>- React Hook Form</p><p>- React toastfy</p><p>- Slate React</p><p><br></p><p>Back-End:</p><p>- BCrypt</p><p>- Cors</p><p>- Express</p><p>- JWT</p><p>- Multer</p><p>- MySql2</p><p>- Sequelize</p>",



}

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({

    lng: "en", // language to use, more information here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
    // you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
    // if you're using a language detector, do not define the lng option
    resources: {
      ptBR: {
        translation: {
          ...ptBR
        }
      }
    },
  });

export default i18n;